### ISSUE TITLE
Set up the Database

### ISSUE THREAD

**Issue by MountBaqer** [Connected-Networks/Connected-Networks-Project#1]
**Requirements**
- [x] initial database code 
- [x] Put tables in mySQL server
- [x] Hookup backend to database

**Acceptance Criteria**
- [x] Can generate queries that create and drop the database with [schema](https://docs.google.com/document/d/10BPz-bHrpYW0ZwAXAMUznG_vumBqZ2VuvMjiApxMWoU/edit?usp=sharing)
- [x] Backend can connect to a local database without errors

**Comment by MountBaqer** [comment]
initial database code requirement got added, look up issue #9 for more details

**Comment by pastorsj** [comment]
@MountBaqer Is this part of the second sprint? If so, please add it to that milestone.
