### ISSUE TITLE
Update update_person and modifyIndividual

### ISSUE THREAD

**Issue by MongoSP** [Connected-Networks/Connected-Networks-Project#122]
The Schema has been changed. the update_person() function in  backend-processing.ts (line 209) & sequelize modifyIndividual() both need to be updated.
**Acceptance Criteria**
- [ ] Updated backend function call
- [ ] Updated Sequelize Function

**Comment by AaronPMichael** [comment]
Upon reflection, the backend function in question doesn't care about column names except when it needs to pass them to the database. Additionally, it doesn't seem logical for a person to change funds. This may not be needed.

**Comment by MongoSP** [comment]
I'll double check tomorrow, but I think the problem was that it tried to call tables that may not exist anymore or columns were out of place (causing it to try to reference foreign keys that didn't exist or where in the wrong order, which freaks sequelize out.)
