### ISSUE TITLE
Fix individual name editing

### ISSUE THREAD

**Issue by AaronPMichael** [Connected-Networks/Connected-Networks-Project#167]
**Acceptance Criteria**
- [ ] User can change the name of an individual

**Comment by MongoSP** [comment]
The bug for this is located in the sequelize modifyIndividual() function; this function was not updated with the current "Overhaul" format. The field IndividualName needs to be renamed to Name, and the originalPosition field has to be removed from this function. Also, the backend needs to be checked to see what it's passing this function, to see if it (and whatever uses it) also needs to be updated.
