### ISSUE TITLE
Integrating frontend with backend to display people

### ISSUE THREAD

**Issue by MountBaqer** [Connected-Networks/Connected-Networks-Project#18]
**Requirements**
- [ ] backend have a API endpoint for the GET request from the frontend
- [ ] frontend makes a GET request for getting people
- [ ] Backend has the getting people logic and responds to the GET request.

**Acceptance Criteria**
- [ ] backend should respond with success status code as well if it was a success and a failure status code otherwise 
- [ ] The format of objects sent from the backend should match the expected format in the frontend

**Comment by DRSisco** [comment]
This might be a good example of breaking the issue into two different issues. 
You could have a backend issue and a separate issue for the frontend. Rarely will you have an issue that hits two different systems.
