### ISSUE TITLE
Finalize SQL Database Tables

### ISSUE THREAD

**Issue by MongoSP** [Connected-Networks/Connected-Networks-Project#21]
- [x] Remove "CurrentCompany" and "CurrentPosition" from Individuals table.
- [x] Add section in Individuals table for the Position the person had when they were added to a fund. (This idea is based on the "Position" label in the Excel example.)
- [x] Determine where to assign items such as Primary and Foreign Keys, Auto-Incrementation of IDs, etc.
- [x] Update TABLE CONSTRUCTION and Dummy Data Construction queries to reflect these new changes to the tables. 
- [x] Finish the Acceptance Criteria for Issue #1, by preparing a SQL Query for dropping the tables in the database.
**Acceptance Criteria**
- [x] The Individuals Table has been updated appropriately and so have all SQL queries related to it. 
- [x] Tables are unable to have duplicate IDs and IDs are auto-assigned when data is inserted.

Date Created:  12/12/19
Estimated Time: 2-1/2 Hours.
Actual Time: 1 hour.
--Comment regarding time: I overestimated how long it would take to research/relearn the aspect of keys and auto incrementing.

**Comment by MongoSP** [comment]
Completed - "Finish the Acceptance Criteria for Issue #1, by preparing a SQL Query for dropping the tables in the database." at 3:40 PM 12/12/19

**Comment by MongoSP** [comment]
Completed  - " Determine where to assign items such as Primary and Foreign Keys, Auto-Incrementation of IDs, etc." at 5:54 PM 12/12/19

**Comment by MongoSP** [comment]
Completed Multiple: 
-Remove "CurrentCompany" and "CurrentPosition" from Individuals table.
-Add section in Individuals table for the Position the person had when they were added to a fund. (This idea is based on the "Position" label in the Excel example.)
-Update TABLE CONSTRUCTION and Dummy Data Construction queries to reflect these new changes to the tables.

Time: 6:01 PM
-

**Comment by MongoSP** [comment]
Competed multiple:
-The Individuals Table has been updated appropriately and so have all SQL queries related to it.
-Tables are unable to have duplicate IDs and IDs are auto-assigned when data is inserted.
Time: 6:11 PM - 12/12/19

**Comment by pastorsj** [comment]
@MongoSP Is this part of a sprint? I see it is being worked on, but it doesn't seem to be part of a sprint.

**Comment by DRSisco** [comment]
closed via #22
