### ISSUE TITLE
Research Sequelize

### ISSUE THREAD

**Issue by MongoSP** [Connected-Networks/Connected-Networks-Project#27]
- [ ] Research the basic uses of Sequelize.
- [x] Install Sequelize
- [x] Ensure that Sequelize can connect to database.
- [ ] Practice with Sequelize.
**Acceptance Criteria**
- [x] At least one group member is able to explain how to use Sequelize.
- [x] Sequelize can connect to project database. 
- [ ] Current Data Creation Queries can be converted to Sequelize.

Date Created: 12/18/19 (To be worked on during Winter Break)
Estimated Time: 3 Hours (Note, this estimate is made after an initial hour of research on the 28th.)

**Comment by MongoSP** [comment]
Completed - "Install Sequelize" at 2:40 PM local time. Total time elapsed was 1 hour.
*Note: The time spent was not solely for the installation of Sequelize, but also encompassed some initial research, storing of links, and local testing. I do not have these local tests stored on our current github for two main reasons: 
     1 - I am essentially just experimenting with Sequelize and becoming familiar with it, 
     learning the basics and such. 
     2 - Before we left for break, we were having a few difficulties concerning merging our
     branches back to milestone 2, a problem I recall had something to do with how 
     node_modules were installed and conflicts emerging from them. As such I do not want
     to branch off our own work until we have that issue resolved. 
I also have managed to get Sequelize to connect to the database, but I do not wish to check off the "Ensure that Sequelize can connect to database." box until I can see that I can actually pull and see data from the database.

**Comment by MongoSP** [comment]
Completed - "Ensure that Sequelize can connect to database." at 3:40 PM local time. Total time elapsed about 40 minutes. (Give or take since I don't think I counted the time it takes to log these here.)

Research was done into Sequelize Models. Of note is that one must mark the primary key and (at this time) disable timestamps in the model (since we have no columns for these in our tables.)
The data from the Individuals table was able to be successfully extracted.

**Comment by DRSisco** [comment]
Closed via #37
