### ISSUE TITLE
Store CSV Data from the Backend to the Database

### ISSUE THREAD

**Issue by KhaledAlfayez237** [Connected-Networks/Connected-Networks-Project#3]
**Requirements**
- [x] Make API endpoint
- [x] Process the data
- [x] Send the data to the backend

**Acceptance Criteria**
- [x] Backend will process the CSV data preparing for database querying.
- [x] Backend will query the database after parsing the CSV data.
- [x] Backend will send responses back to HTTP requests

**Comment by DRSisco** [comment]
This was marked as Done in Sprint2
Can we assign it to that milestone and close it?
