### ISSUE TITLE
Build the "Upload CSV" Frontend Components

### ISSUE THREAD

**Issue by KhaledAlfayez237** [Connected-Networks/Connected-Networks-Project#4]
**Requirements**
- [x] Make the “+” button
- [x] Make the “upload CSV interface”

**Acceptance Criteria**
- [x] I can click on the "+" button to reach the CSV interface
- [x] I can upload a CSV file through the interface

**Comment by pastorsj** [comment]
@KhaledAlfayez237 Please close this issue if it is complete.
