### ISSUE TITLE
Create "FindAll" Functions for Sequelize

### ISSUE THREAD

**Issue by MongoSP** [Connected-Networks/Connected-Networks-Project#58]
To aid with Issue #49, we need to create functions to return the contents of the database to the backend.

**Acceptance Criteria**
- [x] One "FindAll" function is created for each of our existing tables. (Currently 5 tables exist).
- [x] These functions are exportable to the backend with Module.Export

Estimated time: 10 minutes.
Actual Time: 2 hours
--This delay was a result of Sean (me) not realizing that the functions created were returning a promise, which required the use of ".then()" to be used.

**Comment by MongoSP** [comment]
I am testing these functions in a local uncommited file. These tests have revealed that the functions are not preforming as intended. Notably, it seems they run _before_ the connection has been established.

**Comment by DRSisco** [comment]
https://sequelize.org/v5/manual/models-usage.html (Search for `findAll`)
You can just call findAll on your models. If you need to pass conditions, then you will need to add that as an argument. 
These are built in.
