### ISSUE TITLE
Overhaul Database Schema

### ISSUE THREAD

**Issue by MongoSP** [Connected-Networks/Connected-Networks-Project#80]
With new information about the need for multiple users and the interactions between them
**Acceptance Criteria**
- [ ] Schema has been updated to account for multiple users.
- [ ] Schema accounts for an individual appearing in multiple funds from multiple users.
- [ ] Group has looked over this new schema.

**Comment by DRSisco** [comment]
In effort to visualize the current state of the overhaul I made this:
![ConnectedNetworksSchema (1)](https://user-images.githubusercontent.com/19609752/73838128-f5c81b80-47e0-11ea-8918-e9a699c6bdaf.png)

**Comment by DRSisco** [comment]
We should probably discuss this more, but a quick look at the above picture makes me think we should look at going in the following direction. 
@MongoSP lmk your thoughts. I think I need to discuss with @Connected-Networks/clients before making this the formal suggestion on our part.
![Client Proposed Schema](https://user-images.githubusercontent.com/19609752/73843043-d387cb00-47eb-11ea-9d5c-e1efa6ac047e.png)

**Comment by DRSisco** [comment]
Also @Connected-Networks/development-team I know I mentioned SQL naming conventions yesterday during the meeting.
https://launchbylunch.com/posts/2014/Feb/16/sql-naming-conventions/
Everything in this article is pretty standard. You guys don't need to make these changes, but I wanted to make sure you guys had a reference to see those conventions and a little explanation why.

The only exception is the space in the column name, errr "Position Name", "Start Date" , and "End date" are all not acceptable. I would expect those to be fixed. it makes sql references messy and less readable.
