### ISSUE TITLE
backend testing

### ISSUE THREAD

**Issue by AaronPMichael** [Connected-Networks/Connected-Networks-Project#90]
**Acceptance Criteria**
- [x] all functions in backend-processing are called through tests
- [x] all tests pass

**Comment by DRSisco** [comment]
In effort of trying to prevent over-doing this. I would advise only testing code that you have handlers for. Some of the code in backend-processing isn't mapped to a route/handler and thus is not important to the solution as a whole. Though testing all your handlers you should get more than 80% code coverage in the backend. 

If you would like our advice in setting those tests up, I know Sam and I have both setup handler-based tests for an express backend before.
